### ISSUE TITLE
No file output under JRuby 1.6.x

### ISSUE THREAD

**Issue by Boondocks57** [headius/spoon#18]
I attempted to implement sub-process launching using spoon under JRuby 1.6.2 (our project currently requires this version). I do not receive an error but there is no output to the specified file. If I do not add any actions to file_actions then I do get output to the console. I tried to narrow down the version and additionally tried 1.6.4 and 1.6.7.2 and all of them acted the same. But 1.7.2 works flawlessly using the same Spoon 0.0.4 and ffi-1.0.9-java gems and Java 1.6.0_21. I do receive a PID value. I also tried the example code for 'ls -R' with the same result.

**Comment by headius** [comment]
Can you script up a simple reproduction?

**Comment by Boondocks57** [comment]
Charles,

I've attached my test code. Below is the output.

$ jruby --1.9 spawn-test.rb
Using temp file: "/tmp/install_spawn.8059.6295"
ARGV = ["env", "/bin/ls", "-al"]
Spawned process with pid 8078
Zero output!


Thanks,


*Stephen Lutz* | Software Engineer
SeaChange International
50 Nagog Park
Acton, Massachusetts 01720steve.lutz@schange.com | www.schange.com | NASDAQ:
SEAC <http://www.schange.com/en-US/Company/InvestorRelations.aspx>
Office: 9788893017 | Mobile: 9782901123[image: Follow seachangenews on
Twitter] <http://www.twitter.com/seachangenews> [image: Follow SeaChange on
LinkedIn] <http://www.linkedin.com/companies/7525> [image: Follow SeaChange
on FaceBook] <http://www.facebook.com/SeaChangeIntl> [image: SeaChange
Youtube Channel] <http://www.youtube.com/officialseachange>This e-mail and
any attachments may contain information which is SeaChange International
confidential. The information enclosed is intended only for the addressees
herein and may not be copied or forwarded without permission from SeaChange
International.

**Comment by headius** [comment]
File attachments do not get added to Github issues. Use https://gist.github.com please :-)

**Comment by Boondocks57** [comment]
Charles,

Hereis the Gist link: https://gist.github.com/225f2b259a249aa8ac8f.git

Regards,


*Stephen Lutz* | Software Engineer
SeaChange International
50 Nagog Park
Acton, Massachusetts 01720steve.lutz@schange.com | www.schange.com | NASDAQ:
SEAC <http://www.schange.com/en-US/Company/InvestorRelations.aspx>
Office: 9788893017 | Mobile: 9782901123[image: Follow seachangenews on
Twitter] <http://www.twitter.com/seachangenews> [image: Follow SeaChange on
LinkedIn] <http://www.linkedin.com/companies/7525> [image: Follow SeaChange
on FaceBook] <http://www.facebook.com/SeaChangeIntl> [image: SeaChange
Youtube Channel] <http://www.youtube.com/officialseachange>This e-mail and
any attachments may contain information which is SeaChange International
confidential. The information enclosed is intended only for the addressees
herein and may not be copied or forwarded without permission from SeaChange
International.

**Comment by Boondocks57** [comment]
I have been able to hack around this issue. I parsed the /proc/<pid>/fd directory for the descriptor linked to my temp file and used the fd with dup2 to redirect the child STDOUT and STDERR to my temp file. So, I am able to proceed, but it would be nice to have a solution for open before this is fielded.

Thanks.

**Comment by headius** [comment]
Appears to work correctly under JRuby 1.7 and 9k:

```
$ rvm jruby-1.7.25 do jruby blah.rb
Using temp file: "/var/folders/wy/n4rk5qk12nj7q45k0trdqxl40000gn/T/install_spawn20160906-2632-uef7py"
ARGV = ["env", "/bin/ls", "-al"]
Spawned process with pid 2706
  1: total 72
  2: drwxr-xr-x   10 headius  staff    340 Sep  6 09:53 .
  3: drwxr-xr-x  168 headius  staff   5712 Sep  6 09:43 ..
  4: drwxr-xr-x   13 headius  staff    442 Sep  6 09:51 .git
  5: -rw-r--r--    1 headius  staff   9230 Sep  6 09:42 LICENSE
  6: -rw-r--r--    1 headius  staff   1587 Sep  6 09:53 blah.rb
  7: drwxr-xr-x    4 headius  staff    136 Sep  6 09:42 examples
  8: drwxr-xr-x    4 headius  staff    136 Sep  6 09:43 lib
  9: -rw-r--r--    1 headius  staff  10240 Sep  6 09:47 spoon-0.0.5.gem
 10: -rw-r--r--    1 headius  staff    432 Sep  6 09:51 spoon.gemspec
 11: -rw-r--r--    1 headius  staff   2831 Sep  6 09:43 tags
```

If you still see issues on supported JRuby versions (JRuby 1.6 is no longer supported), please open a new issue.
